% File generated by Facile version 0.53a
%
tic;
global ode_tot_cputime;
global ode_num_calls;
ode_tot_cputime = 0.0;
ode_num_calls = 0;

% initial values (free nodes only)
G0401 = 32.8192787251147;
TG00000 = 1000;
G0401_TG00000i00 = 0;
TG00001 = 0;
G0976R = 1.02046391942289;
G0976R_TG00001i01 = 0;
G0976R_TG00000i00 = 0;
G0976T = 0;
G0976T_TG00001i01 = 0;
G0976T_TG00000i00 = 0;
G0000_G0401i00 = 0;
G0000_G0401_TG00000i00 = 0;
G0000_G0976Ri00 = 0;
G0000_G0976R_TG00000i00 = 0;
G0000_G0976Ti00 = 0;
G0000_G0976T_TG00000i00 = 0;
G0000 = 14.9952281952981;
LG0000 = 0.001;
G0000_LG0000i00 = 0;
G0000_G0401_LG0000i00 = 0;
G0000_G0976R_LG0000i00 = 0;
G0000_G0976T_LG0000i00 = 0;
if exist('ivalues') == 0
ivalues = [G0401 TG00000 G0401_TG00000i00 TG00001 G0976R G0976R_TG00001i01 G0976R_TG00000i00 G0976T ...
	G0976T_TG00001i01 G0976T_TG00000i00 G0000_G0401i00 G0000_G0401_TG00000i00 G0000_G0976Ri00 G0000_G0976R_TG00000i00 G0000_G0976Ti00 G0000_G0976T_TG00000i00 ...
	G0000 LG0000 G0000_LG0000i00 G0000_G0401_LG0000i00 G0000_G0976R_LG0000i00 G0000_G0976T_LG0000i00];
end
% rate constants and constant expressions
fb00             = 3.98107170553497;
bb00             = 0.251188643150958;
kp00             = 0.0685136533658775;
fb01             = 1.99526231496888;
bb01             = 0.0158489319246111;
kp01             = 107.710505603677;
fb02             = 1;
kp02             = 530.078483359935;
fb03             = 0.501187233627272;
bb02             = 0.0630957344480193;
kp03             = 226.380340952145;
fb04             = 3.98107170553497;
bb04             = 0.0630957344480193;
fb05             = 1.99526231496888;
bb05             = 0.0158489319246111;
fb06             = 0.501187233627272;
bb06             = 3.98107170553497;
fu07             = 0.353498110503011;
bu07             = 2.13993598573474;
fu08             = 0.62039547525212;
bu08             = 1.88227167521612;
clamp_sink_LG0000 = 4.0;
global ode_rate_constants;
ode_rate_constants = [fb00 bb00 kp00 fb01 bb01 kp01 fb02 kp02 fb03 bb02 kp03 fb04 ...
	bb04 fb05 bb05 fb06 bb06 fu07 bu07 fu08 bu08 clamp_sink_LG0000];

% time interval
t0= 0;
tf= 200000;

% call solver routine 
global event_times;
global event_flags;
ode_events = [0 0 0 0 0 0 0 0 0];
[t, y, intervals]= G057_I00_ode_event(@ode23s, @G057_I00_odes, [t0:1.0:tf], ivalues, odeset(), ode_events, [500.0], [0.001], [1e-06]);


% map free node state vector names
G0401 = y(:,1); TG00000 = y(:,2); G0401_TG00000i00 = y(:,3); TG00001 = y(:,4); G0976R = y(:,5); G0976R_TG00001i01 = y(:,6); G0976R_TG00000i00 = y(:,7); G0976T = y(:,8); G0976T_TG00001i01 = y(:,9); G0976T_TG00000i00 = y(:,10); 
G0000_G0401i00 = y(:,11); G0000_G0401_TG00000i00 = y(:,12); G0000_G0976Ri00 = y(:,13); G0000_G0976R_TG00000i00 = y(:,14); G0000_G0976Ti00 = y(:,15); G0000_G0976T_TG00000i00 = y(:,16); G0000 = y(:,17); LG0000 = y(:,18); G0000_LG0000i00 = y(:,19); G0000_G0401_LG0000i00 = y(:,20); 
G0000_G0976R_LG0000i00 = y(:,21); G0000_G0976T_LG0000i00 = y(:,22); 


if (ode_num_calls > 0)
  ode_avg_cputime = ode_tot_cputime/ode_num_calls*1000;
  str = sprintf('ODE STATS: num ode calls=%d, tot time=%f, avg time=%fms', ode_num_calls, ode_tot_cputime, ode_avg_cputime);
  disp (str)
end


indices=zeros(1,length(event_times));
for i = 1:length(event_times)
indices(i) = find(t<=event_times(i),1,'last');
end

fitness = 0.0001;

for i = 1:length(indices)-1
    range_max=max(TG00001(indices(i):indices(i+1)));
    range_min=min(TG00001(indices(i):indices(i+1)));
    diff=max(abs(range_max-TG00001(indices(i))),abs(range_min-TG00001(indices(i))));
    ss=abs(TG00001(indices(i))-TG00001(indices(i+1)));
    maxdy=(1*10^ceil(i/2));
    fitness=fitness*max(min(diff*2/maxdy,0.99),0.001);
    fitness=fitness*min(abs(1-max(ss*2*10/maxdy,0.0001)),1);
end

fitness = (fitness/0.0001).^(1/(2*(length(indices)-1)));

orig=fitness;


minus10perc=zeros(1,length(ode_rate_constants)-1);

for j = 1:length(ode_rate_constants)-1

ode_rate_constants = [fb00 bb00 kp00 fb01 bb01 kp01 fb02 kp02 fb03 bb02 kp03 fb04 ...
	bb04 fb05 bb05 fb06 bb06 fu07 bu07 fu08 bu08 clamp_sink_LG0000];

ode_rate_constants(j)=ode_rate_constants(j)-0.1*ode_rate_constants(j);


% time interval
t0= 0;
tf= 2000000;

ode_events = [0 0 0 0 0 0 0 0 0];
[t, y, intervals]= G057_I00_ode_event(@ode23s, @G057_I00_odes, [t0:1.0:tf], ivalues, odeset(), ode_events, [500.0], [0.001], [1e-06]);


% map free node state vector names
G0401 = y(:,1); TG00000 = y(:,2); G0401_TG00000i00 = y(:,3); TG00001 = y(:,4); G0976R = y(:,5); G0976R_TG00001i01 = y(:,6); G0976R_TG00000i00 = y(:,7); G0976T = y(:,8); G0976T_TG00001i01 = y(:,9); G0976T_TG00000i00 = y(:,10); 
G0000_G0401i00 = y(:,11); G0000_G0401_TG00000i00 = y(:,12); G0000_G0976Ri00 = y(:,13); G0000_G0976R_TG00000i00 = y(:,14); G0000_G0976Ti00 = y(:,15); G0000_G0976T_TG00000i00 = y(:,16); G0000 = y(:,17); LG0000 = y(:,18); G0000_LG0000i00 = y(:,19); G0000_G0401_LG0000i00 = y(:,20); 
G0000_G0976R_LG0000i00 = y(:,21); G0000_G0976T_LG0000i00 = y(:,22); 

if (ode_num_calls > 0)
  ode_avg_cputime = ode_tot_cputime/ode_num_calls*1000;
  str = sprintf('ODE STATS: num ode calls=%d, tot time=%f, avg time=%fms', ode_num_calls, ode_tot_cputime, ode_avg_cputime);
  disp (str)
end


indices=zeros(1,length(event_times));
for i = 1:length(event_times)
indices(i) = find(t<=event_times(i),1,'last');
end

fitness = 0.0001;

for i = 1:length(indices)-1
    range_max=max(TG00001(indices(i):indices(i+1)));
    range_min=min(TG00001(indices(i):indices(i+1)));
    diff=max(abs(range_max-TG00001(indices(i))),abs(range_min-TG00001(indices(i))));
    ss=abs(TG00001(indices(i))-TG00001(indices(i+1)));
    maxdy=(1*10^ceil(i/2));
    fitness=fitness*max(min(diff*2/maxdy,0.99),0.001);
    fitness=fitness*min(abs(1-max(ss*2*10/maxdy,0.0001)),1);
end

fitness = (fitness/0.0001).^(1/(2*(length(indices)-1)));

minus10perc(j)=fitness;

end



plus10perc=zeros(1,length(ode_rate_constants)-1);
for j = 1:length(ode_rate_constants)-1

ode_rate_constants = [fb00 bb00 kp00 fb01 bb01 kp01 fb02 kp02 fb03 bb02 kp03 fb04 ...
	bb04 fb05 bb05 fb06 bb06 fu07 bu07 fu08 bu08 clamp_sink_LG0000];

ode_rate_constants(j)=ode_rate_constants(j)+0.1*ode_rate_constants(j);


% time interval
t0= 0;
tf= 2000000;

ode_events = [0 0 0 0 0 0 0 0 0];
[t, y, intervals]= G057_I00_ode_event(@ode23s, @G057_I00_odes, [t0:1.0:tf], ivalues, odeset(), ode_events, [500.0], [0.001], [1e-06]);


% map free node state vector names
G0401 = y(:,1); TG00000 = y(:,2); G0401_TG00000i00 = y(:,3); TG00001 = y(:,4); G0976R = y(:,5); G0976R_TG00001i01 = y(:,6); G0976R_TG00000i00 = y(:,7); G0976T = y(:,8); G0976T_TG00001i01 = y(:,9); G0976T_TG00000i00 = y(:,10); 
G0000_G0401i00 = y(:,11); G0000_G0401_TG00000i00 = y(:,12); G0000_G0976Ri00 = y(:,13); G0000_G0976R_TG00000i00 = y(:,14); G0000_G0976Ti00 = y(:,15); G0000_G0976T_TG00000i00 = y(:,16); G0000 = y(:,17); LG0000 = y(:,18); G0000_LG0000i00 = y(:,19); G0000_G0401_LG0000i00 = y(:,20); 
G0000_G0976R_LG0000i00 = y(:,21); G0000_G0976T_LG0000i00 = y(:,22); 


%subplot(2,1,1); semilogy(t,LG0000); ylim([0.1, 1000]);subplot(2,1,2); plot(t,TG00001);

if (ode_num_calls > 0)
  ode_avg_cputime = ode_tot_cputime/ode_num_calls*1000;
  str = sprintf('ODE STATS: num ode calls=%d, tot time=%f, avg time=%fms', ode_num_calls, ode_tot_cputime, ode_avg_cputime);
  disp (str)
end

indices=zeros(1,length(event_times));
for i = 1:length(event_times)
indices(i) = find(t<=event_times(i),1,'last');
end

fitness = 0.0001;

for i = 1:length(indices)-1
    range_max=max(TG00001(indices(i):indices(i+1)));
    range_min=min(TG00001(indices(i):indices(i+1)));
    diff=max(abs(range_max-TG00001(indices(i))),abs(range_min-TG00001(indices(i))));
    ss=abs(TG00001(indices(i))-TG00001(indices(i+1)));
    maxdy=(1*10^ceil(i/2));
    fitness=fitness*max(min(diff*2/maxdy,0.99),0.001);
    fitness=fitness*min(abs(1-max(ss*2*10/maxdy,0.0001)),1);
end

fitness = (fitness/0.0001).^(1/(2*(length(indices)-1)));

plus10perc(j)=fitness;

end

up10perc=(plus10perc - orig)./orig;
down10perc=(minus10perc - orig)./orig;
bar(transpose([down10perc;up10perc]));

