% File generated by Facile version 0.53a
%
tic;
global ode_tot_cputime;
global ode_num_calls;
ode_tot_cputime = 0.0;
ode_num_calls = 0;

% initial values (free nodes only)
G0401 = 2.20347691230698;
TG00000 = 9.99999999999999;
G0401_TG00000i00 = 0;
TG00001 = 0;
G080200 = 9.99999999999999;
G080200_TG00001i00 = 0;
G0000_G0401i00 = 0;
G0000_G0401_TG00000i00 = 0;
G0000_G080200i00 = 0;
G0000_G080200_TG00001i00 = 0;
G0000_G080200i01 = 0;
G0000_G080200_TG00001i01 = 0;
G0000 = 9.99999999999999;
G0000_G080200i02 = 0;
LG0000 = 0.001;
G0000_LG0000i00 = 0;
G0000_G0000_G080200i00 = 0;
G0000_G0000_G080200i01 = 0;
G0000_G0000_G080200i02 = 0;
G0000_G0401_LG0000i00 = 0;
G0000_G080200_LG0000i00 = 0;
G0000_G080200_LG0000i01 = 0;
G0000_G080200_LG0000i02 = 0;
if exist('ivalues') == 0
ivalues = [G0401 TG00000 G0401_TG00000i00 TG00001 G080200 G080200_TG00001i00 G0000_G0401i00 G0000_G0401_TG00000i00 ...
	G0000_G080200i00 G0000_G080200_TG00001i00 G0000_G080200i01 G0000_G080200_TG00001i01 G0000 G0000_G080200i02 LG0000 G0000_LG0000i00 ...
	G0000_G0000_G080200i00 G0000_G0000_G080200i01 G0000_G0000_G080200i02 G0000_G0401_LG0000i00 G0000_G080200_LG0000i00 G0000_G080200_LG0000i01 G0000_G080200_LG0000i02];
end
% rate constants and constant expressions
fb00             = 0.125892541179417;
bb00             = 0.501187233627272;
kp00             = 0.586581613397342;
fb01             = 1;
bb01             = 1;
kp01             = 0.0415688804861519;
fb02             = 1;
bb02             = 0.0630957344480193;
fb03             = 1.99526231496888;
bb03             = 0.501187233627272;
fb04             = 1;
bb04             = 0.251188643150958;
fb05             = 1.99526231496888;
bb05             = 1.99526231496888;
fb06             = 0.0630957344480194;
bb06             = 3.98107170553497;
clamp_sink_LG0000 = 4.0;
global ode_rate_constants;
ode_rate_constants = [fb00 bb00 kp00 fb01 bb01 kp01 fb02 bb02 fb03 bb03 fb04 bb04 ...
	fb05 bb05 fb06 bb06 clamp_sink_LG0000];

% time interval
t0= 0;
tf= 20000;

% call solver routine 
global event_times;
global event_flags;
ode_events = [0 0 0 0 0 0 0 0 0];
[t, y, intervals]= G028_I00_ode_event(@ode23s, @G028_I00_odes, [t0:1.0:tf], ivalues, odeset(), ode_events, [500.0], [0.001], [1e-06]);


% map free node state vector names
G0401 = y(:,1); TG00000 = y(:,2); G0401_TG00000i00 = y(:,3); TG00001 = y(:,4); G080200 = y(:,5); G080200_TG00001i00 = y(:,6); G0000_G0401i00 = y(:,7); G0000_G0401_TG00000i00 = y(:,8); G0000_G080200i00 = y(:,9); G0000_G080200_TG00001i00 = y(:,10); 
G0000_G080200i01 = y(:,11); G0000_G080200_TG00001i01 = y(:,12); G0000 = y(:,13); G0000_G080200i02 = y(:,14); LG0000 = y(:,15); G0000_LG0000i00 = y(:,16); G0000_G0000_G080200i00 = y(:,17); G0000_G0000_G080200i01 = y(:,18); G0000_G0000_G080200i02 = y(:,19); G0000_G0401_LG0000i00 = y(:,20); 
G0000_G080200_LG0000i00 = y(:,21); G0000_G080200_LG0000i01 = y(:,22); G0000_G080200_LG0000i02 = y(:,23); 





if (ode_num_calls > 0)
  ode_avg_cputime = ode_tot_cputime/ode_num_calls*1000;
  str = sprintf('ODE STATS: num ode calls=%d, tot time=%f, avg time=%fms', ode_num_calls, ode_tot_cputime, ode_avg_cputime);
  disp (str)
end

% issue done message for calling/wrapper scripts
str = sprintf('Facile driver script done (elapsed time %f)',toc);
disp (str)

